### ISSUE TITLE
AttributeError: module 'keras.api.backend' has no attribute 'square'

### ISSUE THREAD

**Issue by Rohit-Satyam** [mikelkou/fava#22]
Hi @grst @mikelkou 

Greetings!!
I am facing issues in installing the favapy using the following steps. It's quite frustrating to figure out what Tensorflow, Keras and python versions your tool uses (and I couldn't find it in the documentation), so I am reaching out to you about this. Could you please provide this information? 

```bash
mamba create -n favpy -c conda-forge -c bioconda python tensorflow-gpu
pip install favapy
```

```bash
favapy --data_type csv -c 1 Gubbels.csv .
2024-12-24 20:00:31.597161: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-24 20:00:31.615304: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-24 20:00:31.639273: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-24 20:00:31.646215: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-24 20:00:31.661989: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-24 20:00:33.427297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 17615 MB memory:  -> device: 0, name: NVIDIA RTX A4500, pci bus id: 0000:4b:00.0, compute capability: 8.6
2024-12-24 20:00:39.813053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 17615 MB memory:  -> device: 0, name: NVIDIA RTX A4500, pci bus id: 0000:4b:00.0, compute capability: 8.6
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1735059640.529359  804019 gpu_backend_lib.cc:593] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
Searched for CUDA in the following directories:
  ./cuda_sdk_lib
  /home/conda/feedstock_root/build_artifacts/tensorflow-split_1729076995378/_build_env/targets/x86_64-linux
  /usr/local/cuda
  /home/subudhak/miniconda3/envs/favpy/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc
  /home/subudhak/miniconda3/envs/favpy/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc
  .
You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/favpy/bin/favapy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/subudhak/miniconda3/envs/favpy/lib/python3.12/site-packages/favapy/fava.py", line 521, in main
    vae = VAE(
          ^^^^
  File "/home/subudhak/miniconda3/envs/favpy/lib/python3.12/site-packages/favapy/fava.py", line 213, in __init__
    kl_loss = 1 + z_log_sigma - K.square(z_mean) - K.exp(z_log_sigma)
                                ^^^^^^^^
AttributeError: module 'keras.api.backend' has no attribute 'square'

```

```bash
pip show tensorflow keras
Name: tensorflow
Version: 2.17.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/subudhak/miniconda3/envs/favpy/lib/python3.12/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, ml-dtypes, opt-einsum, packaging, protobuf, requests, setuptools, six, tensorboard, termcolor, typing-extensions, wrapt
Required-by: favapy
---
Name: keras
Version: 3.7.0
Summary: Multi-backend Keras
Home-page: 
Author: 
Author-email: Keras team <keras-users@googlegroups.com>
License: Apache License 2.0
Location: /home/subudhak/miniconda3/envs/favpy/lib/python3.12/site-packages
Requires: absl-py, h5py, ml-dtypes, namex, numpy, optree, packaging, rich
Required-by: favapy, tensorflow

```

**Comment by Rohit-Satyam** [comment]
Tried the following but encountered a new kind of error:


```bash
mamba create -n favpy -c conda-forge -c bioconda python tensorflow-gpu=2.13 keras=2.13
```

```bash
2024-12-24 20:20:14.993476: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-24 20:20:15.053118: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-24 20:20:16.695515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 17421 MB memory:  -> device: 0, name: NVIDIA RTX A4500, pci bus id: 0000:4b:00.0, compute capability: 8.6
2024-12-24 20:20:23.902146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 17421 MB memory:  -> device: 0, name: NVIDIA RTX A4500, pci bus id: 0000:4b:00.0, compute capability: 8.6
Epoch 1/50
2024-12-24 20:20:27.133724: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:606] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2024-12-24 20:20:27.214119: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14c3d86f53a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-12-24 20:20:27.214163: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA RTX A4500, Compute Capability 8.6
2024-12-24 20:20:27.220622: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-12-24 20:20:27.238047: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8907
2024-12-24 20:20:27.268465: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:543] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
Searched for CUDA in the following directories:
  ./cuda_sdk_lib
  /usr/local/cuda-11.8
  /usr/local/cuda
  .
You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2024-12-24 20:20:27.268869: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.270005: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.298093: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.299242: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.326336: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.327314: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.354963: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.355955: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.384675: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.385772: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.410502: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.411488: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.437653: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.438666: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.466102: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.467246: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.495654: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.496733: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
2024-12-24 20:20:27.525386: W tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:273] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
2024-12-24 20:20:27.526503: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : INTERNAL: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/favpy/bin/favapy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/favapy/fava.py", line 521, in main
    vae = VAE(
          ^^^^
  File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/favapy/fava.py", line 220, in __init__
    vae.fit(
  File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'Adam/StatefulPartitionedCall_9' defined at (most recent call last):
    File "/home/subudhak/miniconda3/envs/favpy/bin/favapy", line 8, in <module>
      sys.exit(main())
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/favapy/fava.py", line 521, in main
      vae = VAE(
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/favapy/fava.py", line 220, in __init__
      vae.fit(
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/engine/training.py", line 1742, in fit
      tmp_logs = self.train_function(iterator)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/engine/training.py", line 1338, in train_function
      return step_function(self, iterator)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/engine/training.py", line 1322, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/engine/training.py", line 1303, in run_step
      outputs = model.train_step(data)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/engine/training.py", line 1084, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 544, in minimize
      self.apply_gradients(grads_and_vars)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 1230, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 652, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 1260, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 1352, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/home/subudhak/miniconda3/envs/favpy/lib/python3.11/site-packages/keras/src/optimizers/optimizer.py", line 1347, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'Adam/StatefulPartitionedCall_9'
libdevice not found at ./libdevice.10.bc
	 [[{{node Adam/StatefulPartitionedCall_9}}]] [Op:__inference_train_function_2222]

```

**Comment by Rohit-Satyam** [comment]
I was able to fix the installation issue as follows using the solution provided [here](https://github.com/tensorflow/tensorflow/issues/58681#issuecomment-1406967453). It would be nice to add this in the README for people who use Conda

```bash
mamba create -n favpy -c conda-forge -c bioconda python tensorflow-gpu=2.13 keras=2.13
mamba activate favpy
pip install favapy
mamba install -c conda-forge cudatoolkit cudnn
mamba install -c conda-forge cudatoolkit-dev ## Didn't help
mamba install -c nvidia cuda-nvcc ## Didn't help 
mkdir -p $CONDA_PREFIX/lib/nvvm/libdevice/
cp -p $CONDA_PREFIX/lib/libdevice.10.bc $CONDA_PREFIX/lib/nvvm/libdevice/
export XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib
export TF_ENABLE_ONEDNN_OPTS=0
```

**Comment by Rohit-Satyam** [comment]
I now have a different question: I see that when I ran favapy I get different correlation coefficient for same pair of gene (BTW this is parasite single cell and the input matrix contains different cell types because I want to understand irrespective of cell types if two genes are co-expressed or not). Do you recommend running it in replicates (something like 50 times) and then get a mean? Another thing is the loss and accuracy as can be seen below. It appears that 50 epochs are not sufficient right? Should I try higher? Can you explain more about the batch parameter? Is it the no of cells samples in each apoch?


```
Epoch 49/50
210/210 [==============================] - 3s 16ms/step - loss: 75.1967 - accuracy: 0.0617 - val_loss: 73.9127 - val_accuracy: 0.0639
Epoch 50/50
210/210 [==============================] - 3s 16ms/step - loss: 74.6980 - accuracy: 0.0608 - val_loss: 73.3005 - val_accuracy: 0.0679
210/210 [==============================] - 1s 3ms/step

```

**Comment by Rohit-Satyam** [comment]
Even after 500 epochs, I couldn't see improved accuracy `favapy --data_type csv -e 500 -b 100 -n 100000000 Gubbels.csv gubbels_results4`. Even for 1000 epochs the loss appears to be stuck at 35% and accuracy at 0.2 even when I increase batch to 1000.

```
68/68 [==============================] - 1s 21ms/step - loss: 35.0908 - accuracy: 0.2055 - val_loss: 34.8108 - val_accuracy: 0.2155
Epoch 499/500
68/68 [==============================] - 1s 21ms/step - loss: 34.9863 - accuracy: 0.2131 - val_loss: 35.0836 - val_accuracy: 0.2068
Epoch 500/500
68/68 [==============================] - 1s 19ms/step - loss: 35.0092 - accuracy: 0.2122 - val_loss: 34.5752 - val_accuracy: 0.2223
68/68 [==============================] - 0s 4ms/step
INFO:root: Calculating pearson correlation scores.
Total time taken OLD: 4.566844701766968 seconds
WARNING:root: The number of interactions in the output file is 100000000 in which both directions are included: proteinA - proteinB and proteinB - proteinA.

```

**Comment by Rohit-Satyam** [comment]
Please replay at your convenience (I understand it festive season so there is no rush). Adding this observation 

```
favapy --data_type csv -e 300 -b 16 -n 120000 Gubbels.csv gubbels_results_data_filtered -l 400 -d 1200
```

@grst @mikelkou So I played around a little. I filtered out the genes with less than 5 read counts that are not captured in at least 50 cells. I also removed cells with less than 50 genes with counts >5. This leaves me with ~330 genes and ~2100 cells. I tested various `-e` and `-b` values and could reduce the loss to 11.5 and increase accuracy up to 0.67 using `-e 300` and `-b 16`. However, it doesn't get better than this. I played with the parameters `-d` and `-l` (increased -d from 1200 to 2000` and -l from 200 to 400) but the loss oscillates near 10-11% with accuracy struggling between 0.6 and 0.7. What else can be done? 

**Edit1:**

```
favapy --data_type csv -e 2000 -b 16 -n 120000 Gubbels.csv gubbels_results_data_filtered -l 300
Epoch 2000/2000
21/21 [==============================] - 0s 18ms/step - loss: 5.8848 - accuracy: 0.7259 - val_loss: 5.2807 - val_accuracy: 0.7380
``` 

**Edit2:**
When I try using the Python package rather than the CLI interface, the story is entirely different. I easily get high accuracy with the `1000` epochs and `-b 16`. So there is some issue with the CLI.


```
data = pd.read_csv("./Gubbels.csv", sep=",",index_col=0)
my_FAVAourite_network = fava.cook(
    data=data,
    log2_normalization=False,  # If your data are normalized set this to False
    hidden_layer=None,  # If None, it will be adjusted base on the input size.
    latent_dim=None,  # If None, it will be adjusted base on the size of the hidden layer.
    epochs=1000,
    batch_size=16,
    interaction_count=120000
) 
```

```
Epoch 998/1000
11/11 [==============================] - 0s 21ms/step - loss: 2.8712 - accuracy: 0.8283 - val_loss: 2.7812 - val_accuracy: 0.8313
Epoch 999/1000
11/11 [==============================] - 0s 22ms/step - loss: 2.8758 - accuracy: 0.8645 - val_loss: 2.7440 - val_accuracy: 0.8404
Epoch 1000/1000
11/11 [==============================] - 0s 22ms/step - loss: 2.8254 - accuracy: 0.8434 - val_loss: 2.6993 - val_accuracy: 0.8253


```

**Comment by mikelkou** [comment]
Hi,

Thanks for the detailed feedback! The difference in performance between the CLI and Python package could be due to a few factors:

Defaults: The CLI might use different default values for parameters like hidden_layer or latent_dim. Try setting them explicitly in your CLI command.
Preprocessing: The CLI might handle preprocessing differently. If you've filtered or preprocessed the data manually, ensure the CLI isn't applying additional steps.
Implementation Issue: There might be a discrepancy in how the CLI and Python package handle the model training.
I'll check the CLI implementation to see if there's a bug. In the meantime, you could try aligning the CLI parameters more closely with what worked in the Python package, like:

`favapy --data_type csv -e 1000 -b 16 -n 120000 Gubbels.csv gubbels_results_data_filtered --hidden_layer 512 --latent_dim 128`

About accuracy: while it’s easy to understand, it might not fully reflect performance, especially if the dataset is imbalanced. Consider checking metrics like precision, recall, F1-score, or AUROC for a clearer picture.

Let me know if this helps or if you have any other insights!

**Comment by Rohit-Satyam** [comment]
Will investigate this and get back to you. 

**Edit1**
@mikelkou 

I tried your recommendation and still the loss is stuck at 11% for CLI.

```
favapy --data_type csv -e 1000 -b 16 -n 120000 /phd/Gubbels.csv gubbels_results_data_filtered -l 128 -d 512
Epoch 1000/1000
21/21 [==============================] - 0s 17ms/step - loss: 11.8753 - accuracy: 0.5964 - val_loss: 11.3658 - val_accuracy: 0.5843
21/21 [==============================] - 0s 3ms/step
INFO:root: Calculating pearson correlation scores.
Total time taken OLD: 0.048340559005737305 seconds
WARNING:root: The number of interactions in the output file is 120000 in which both directions are included: proteinA - proteinB and proteinB - proteinA.
```

How important is it for the loss to be near zero and accuracy to be greater than 0.9 for fava? What are your recommendation beyond which we can stop sweating about it?

**Edit2**

I can share the `Gubbels.csv` since its a public dataset if you are willing to debug it. Kindly let me know your email id.

**Comment by Rohit-Satyam** [comment]
Hi @mikelkou. Were you able to test it. Should I provide you with the data I am working with?

**Comment by Rohit-Satyam** [comment]
Hi @mikelkou Could you please resolve my pending queries?

**Comment by Rohit-Satyam** [comment]
@mikelkou @grst Any input would be appreciated.

**Comment by mikelkou** [comment]
Hi Rohit, apologies as I have stopped the active maintenance of the package. It still runs on my end. Let me know again what your status is?

**Comment by Rohit-Satyam** [comment]
Can you comment about my accuracy related doubt?

**Comment by mikelkou** [comment]
Neither is a universal target for FAVA (or any ML model). What matters is generalization on a held-out set and improvement over a simple baseline for your task.

Loss ≈ 0 is not required. Very low training loss often signals overfitting. I care about validation loss plateauing (or improving) and a small train–val gap.

Accuracy > 0.9 is only meaningful if the task is easy and/or balanced. For class-imbalanced data, accuracy can be misleading—prefer AUPRC (and AUROC) along with per-class precision/recall.
